# Geocoding

In [1]:
import geopandas as gpds
import pandas as pd
import numpy as np

In [2]:
gpds.tools.geocode('Brasilia,DF',provider='nominatim',user_agent='teste_passdriver')

geometry  \
0  POINT (-47.88232 -15.79340)   

                                             address  
0  Brasília, Região Integrada de Desenvolvimento ...

In [3]:
end = pd.read_csv('endereco.csv',encoding='UTF-8')
end

ponto                                           endereco
0  ponto01  Estrada Parque Ceilândia, SIA, Região Integrad...
1  ponto02  QSB 12, Taguatinga, Região Integrada de Desenv...
2  ponto03  Bloco A / B, W1 Sul, SQS 104, Asa Sul, Brasíli...
3  ponto04  Recanto das Emas, Região Integrada de Desenvol...

In [4]:
gpds.tools.geocode(end['endereco'],provider='nominatim',user_agent='teste_passdriver',country_bias='Brazil')

geometry  \
0  POINT (-47.98341 -15.78920)   
1  POINT (-48.05318 -15.83996)   
2  POINT (-47.89561 -15.80715)   
3  POINT (-48.06078 -15.90255)   

                                             address  
0  EPCL, SIA, Região Integrada de Desenvolvimento...  
1  QSB 12, Taguatinga, Região Integrada de Desenv...  
2  Bloco A / B, W1 Sul, SQS 104, Asa Sul, Plano P...  
3  Recanto das Emas, Região Integrada de Desenvol...

In [4]:
end['Geom'] = gpds.tools.geocode(end['endereco'], provider = "nominatim", user_agent="Intro Geocode", country_bias="Brazil")['geometry']

In [5]:
end.Geom

0    POINT (-47.98341 -15.78920)
1    POINT (-48.05318 -15.83996)
2    POINT (-47.89561 -15.80715)
3    POINT (-48.06078 -15.90255)
Name: Geom, dtype: geometry

# Geocode reverse address

In [6]:
import shapely.geometry
import geopy

In [7]:
end["Geom"][0].x

-47.9834114

In [8]:
end["Geom"][0].y

-15.7892025

In [9]:
geopy.geocoders.osm.Nominatim(user_agent="Intro Geocode").reverse(str(end["Geom"][0].y) + ", " + str(end["Geom"][0].x))

Location(EPCL, SIA, Região Integrada de Desenvolvimento do Distrito Federal e Entorno, DF, Região Centro-Oeste, 71250005, Brasil, (-15.7892025, -47.9834114, 0.0))

In [10]:
end["y"] = end["Geom"].map(lambda p: p.y)
end["x"] = end["Geom"].map(lambda p: p.x)
end["yx"] = end["Geom"].map(lambda p: str(p.y) + ", " + str(p.x))

# passdriver server connect

In [11]:
# geopy.geocoders.osm.passdriver = 'https://1c3ff67uttr.ngrok.io'
# geopy.geocoders.SERVICE_TO_GEOCODER = {'passdriver':geopy.geocoders.osm.passdriver}

In [12]:
end.head()

ponto                                           endereco  \
0  ponto01  Estrada Parque Ceilândia, SIA, Região Integrad...   
1  ponto02  QSB 12, Taguatinga, Região Integrada de Desenv...   
2  ponto03  Bloco A / B, W1 Sul, SQS 104, Asa Sul, Brasíli...   
3  ponto04  Recanto das Emas, Região Integrada de Desenvol...   

                          Geom          y          x  \
0  POINT (-47.98341 -15.78920) -15.789203 -47.983411   
1  POINT (-48.05318 -15.83996) -15.839957 -48.053179   
2  POINT (-47.89561 -15.80715) -15.807154 -47.895610   
3  POINT (-48.06078 -15.90255) -15.902548 -48.060778   

                               yx  
0        -15.7892025, -47.9834114  
1        -15.8399567, -48.0531795  
2  -15.8071537, -47.8956104207204  
3        -15.9025481, -48.0607778

In [14]:
geopy.geocoders.osm.Nominatim(user_agent="Intro Geocode").reverse(end[0:1]["yx"])

Location(EPCL, SIA, Região Integrada de Desenvolvimento do Distrito Federal e Entorno, DF, Região Centro-Oeste, 71250005, Brasil, (-15.7892025, -47.9834114, 0.0))

In [15]:
end['RevAddress'] = end.apply(lambda row: geopy.geocoders.osm.Nominatim(user_agent="Intro Geocode").reverse(row['yx']),axis=1)

In [16]:
end.head()

ponto                                           endereco  \
0  ponto01  Estrada Parque Ceilândia, SIA, Região Integrad...   
1  ponto02  QSB 12, Taguatinga, Região Integrada de Desenv...   
2  ponto03  Bloco A / B, W1 Sul, SQS 104, Asa Sul, Brasíli...   
3  ponto04  Recanto das Emas, Região Integrada de Desenvol...   

                          Geom          y          x  \
0  POINT (-47.98341 -15.78920) -15.789203 -47.983411   
1  POINT (-48.05318 -15.83996) -15.839957 -48.053179   
2  POINT (-47.89561 -15.80715) -15.807154 -47.895610   
3  POINT (-48.06078 -15.90255) -15.902548 -48.060778   

                               yx  \
0        -15.7892025, -47.9834114   
1        -15.8399567, -48.0531795   
2  -15.8071537, -47.8956104207204   
3        -15.9025481, -48.0607778   

                                          RevAddress  
0  (EPCL, SIA, Região Integrada de Desenvolviment...  
1  (QSB 13, Taguatinga, Região Integrada de Desen...  
2  (Bloco A / B, W1 Sul, SQS 104, Asa Sul, Plano ...  
3  (Recanto das Emas, Região Integrada de Desenvo...

In [17]:
geopy.geocoders.SERVICE_TO_GEOCODER

{'passdriver': 'https://1c3ff67uttr.ngrok.io'}

# OSRM

In [13]:
import osrm_plus

In [14]:
test_coordinates = [
    "-47.98341,-15.78920",
    "-48.05318,-15.83996",
    "-47.89561,-15.80715",
    "-48.06078,-15.90255"
]

In [15]:
route_info = osrm_plus.distances_and_durations(test_coordinates, include_speed=True)
distances = np.round(route_info['distances'])
durations = np.round(route_info['durations'])
speeds = np.round(route_info['speeds'])

In [16]:
print("Distance matrix: \n\t{}".format(distances))
print("Duration matrix: \n\t{}".format(durations))
print("Speed matrix (m/s): \n\t{}".format(speeds))
print("Speed matrix (km/h): \n\t{}".format(speeds*((60*60)/1000)))

Distance matrix: 
	[[    0. 12818. 13991. 22749.]
 [12818.     0. 24006. 13382.]
 [13991. 24006.     0. 34144.]
 [22749. 13382. 34144.     0.]]
Duration matrix: 
	[[   0.  888.  995. 1521.]
 [ 888.    0. 1690. 1181.]
 [ 995. 1690.    0. 1992.]
 [1521. 1181. 1992.    0.]]
Speed matrix (m/s): 
	[[ 0. 14. 14. 15.]
 [14.  0. 14. 11.]
 [14. 14.  0. 17.]
 [15. 11. 17.  0.]]
Speed matrix (km/h): 
	[[ 0.  50.4 50.4 54. ]
 [50.4  0.  50.4 39.6]
 [50.4 50.4  0.  61.2]
 [54.  39.6 61.2  0. ]]


In [17]:
test_coordinates = [
    "-47.98341,-15.78920",
    "-48.06078,-15.90255"
]
route_info = osrm_plus.distances_and_durations(test_coordinates, include_speed=True)
distances = np.round(route_info['distances'])
durations = np.round(route_info['durations'])
speeds = np.round(route_info['speeds'])
print("Distance matrix: \n\t{}".format(distances))
print("Duration matrix: \n\t{}".format(durations))
print("Speed matrix (m/s): \n\t{}".format(speeds))
print("Speed matrix (km/h): \n\t{}".format(speeds*((60*60)/1000)))

Distance matrix: 
	[[    0. 22749.]
 [22749.     0.]]
Duration matrix: 
	[[   0. 1521.]
 [1521.    0.]]
Speed matrix (m/s): 
	[[ 0. 15.]
 [15.  0.]]
Speed matrix (km/h): 
	[[ 0. 54.]
 [54.  0.]]


# MAPS WHIT FOLIUM

In [26]:
import folium

In [27]:
m = folium.Map(location=[-15.79340,-47.88232],zoom_start=11)
m